### ISSUE TITLE
systemd units

### ISSUE THREAD

**Issue by cyb3ralbert** [TheDave1022/ZoneMinder_TelegramAlertNotifier#1]
I can't find it. Should I write them by myself. Respect

**Comment by TheDave1022** [comment]
I updated the files. See 
https://github.com/TheDave1022/ZoneMinder_TelegramAlertNotifier/blob/main/etc/systemd/system/zm_telegram.service

Sorry about the delayed response

**Comment by cyb3ralbert** [comment]
thanks. a good job!
