### ISSUE TITLE
Missing zm_telegram.service

### ISSUE THREAD

**Issue by VictorvandenHoven** [TheDave1022/ZoneMinder_TelegramAlertNotifier#2]
I am trying this out, but zm_telegram.service seems to be missing?

**Comment by TheDave1022** [comment]
It should be zm_telegram_service.sh

I just added the file. Please see 
https://github.com/TheDave1022/ZoneMinder_TelegramAlertNotifier/blob/main/etc/systemd/system/zm_telegram.service
